services:
  frontend:
    image: ghcr.io/danielbras77/cloud-frontend:latest
  api:
    image: ghcr.io/danielbras77/cloud-api:latest
    environment:
      - DB_USER=admin
      - DB_PASSWORD=mysecurepassword
      - DB_NAME=users_db
      - DB_HOST=database
  proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./data/npm:/data
      - ./data/letsencrypt:/etc/letsencrypt
  database:
    image: postgres:alpine
    volumes:
      - db_data:/var/lib/postgresql/18/docker
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mysecurepassword
      - POSTGRES_DB=users_db
  minio-storage:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data

volumes:
  db_data:
  minio_data: